version: '3'
services:
  react:
    build:
      context: ./play-react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"